name: "Build and Deploy WebApi"

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: powukraine-webapi
  AZURE_WEBAPP_PACKAGE_PATH: "./published"
  NETCORE_VERSION: "5.0.x"

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Publish app for deploy
        run: dotnet publish ./Pow.WebApi --no-build -c Release -o ./published

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DOTNET }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}